### ISSUE TITLE
Working on Similar Problem To Help Community |  Code & Dataset

### ISSUE THREAD

**Issue by muhammadabdullah34907** [CAMERA-Bath/RGBD-Dog#1]
Hi @CAMERA-Bath 
 I am working on similar project to help community to alter dog pooping in their areas. For that I am looking for various pose estimation projects to also consider the pose or joints of dogs to improve the results. I will be very thankful if you could share the code and dataset as soon as possible.

**Comment by CAMERA-Bath** [comment]
Hi there
Data should be available June latest + the possibility of code once we are up and running on the data. Definitely check around CVPR time again (latest) as things will be up by then (data 100%)
Best
Darren

**Comment by CAMERA-Bath** [comment]
Hello,
The data has now been uploaded. Details on accessing the data are given at [https://github.com/CAMERA-Bath/RGBD-Dog#access](https://github.com/CAMERA-Bath/RGBD-Dog#access)

Sinéad.
