### ISSUE TITLE
dog smpl model

### ISSUE THREAD

**Issue by zhangluustb** [CAMERA-Bath/RGBD-Dog#2]
Thank you for your sharing. Could you please release your dog model? THANK YOU.

**Comment by sineadkearney** [comment]
Hello, you can access the model and data for academic purposes by filling in the form Data_Release_Form_RGBDDog_CVPR_2020.pdf (found in this repo) and email it to me at sk2007@bath.ac.uk. For commercial purposes, you can contact Prof. Darren Cosker at d.p.cosker@bath.ac.uk.
